In [1]:
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd 

In [2]:
#load the dataset
data_set= pd.read_csv("D:/Dataset/Salary_dataset.csv") #/content/Salary_dataset.csv
print(data_set.head())

   Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0


In [3]:
data_set.tail()

Unnamed: 0  YearsExperience    Salary
25          25              9.1  105583.0
26          26              9.6  116970.0
27          27              9.7  112636.0
28          28             10.4  122392.0
29          29             10.6  121873.0

In [4]:
data_set.sample(15)

Unnamed: 0  YearsExperience    Salary
2            2              1.6   37732.0
29          29             10.6  121873.0
6            6              3.1   60151.0
24          24              8.8  109432.0
19          19              6.1   93941.0
10          10              4.0   63219.0
14          14              4.6   61112.0
15          15              5.0   67939.0
4            4              2.3   39892.0
28          28             10.4  122392.0
3            3              2.1   43526.0
20          20              6.9   91739.0
23          23              8.3  113813.0
12          12              4.1   56958.0
11          11              4.1   55795.0

In [5]:
data_set=data_set.drop(columns='Unnamed: 0')

In [6]:
data_set.head(10)

YearsExperience   Salary
0              1.2  39344.0
1              1.4  46206.0
2              1.6  37732.0
3              2.1  43526.0
4              2.3  39892.0
5              3.0  56643.0
6              3.1  60151.0
7              3.3  54446.0
8              3.3  64446.0
9              3.8  57190.0

In [7]:
data_set.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.413333   76004.000000
std           2.837888   27414.429785
min           1.200000   37732.000000
25%           3.300000   56721.750000
50%           4.800000   65238.000000
75%           7.800000  100545.750000
max          10.600000  122392.000000

In [8]:
data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 608.0 bytes


In [9]:
data_set.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [10]:
data_set.duplicated().sum()

0

In [11]:
x= data_set.iloc[:, :-1].values
y= data_set.iloc[:, -1].values 
print(x)
print(y)

[[ 1.2]
 [ 1.4]
 [ 1.6]
 [ 2.1]
 [ 2.3]
 [ 3. ]
 [ 3.1]
 [ 3.3]
 [ 3.3]
 [ 3.8]
 [ 4. ]
 [ 4.1]
 [ 4.1]
 [ 4.2]
 [ 4.6]
 [ 5. ]
 [ 5.2]
 [ 5.4]
 [ 6. ]
 [ 6.1]
 [ 6.9]
 [ 7.2]
 [ 8. ]
 [ 8.3]
 [ 8.8]
 [ 9.1]
 [ 9.6]
 [ 9.7]
 [10.4]
 [10.6]]
[ 39344.  46206.  37732.  43526.  39892.  56643.  60151.  54446.  64446.
  57190.  63219.  55795.  56958.  57082.  61112.  67939.  66030.  83089.
  81364.  93941.  91739.  98274. 101303. 113813. 109432. 105583. 116970.
 112636. 122392. 121873.]


In [12]:
# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 1/3, random_state=0)

In [13]:
x_train

array([[ 3. ],
       [ 5.2],
       [ 3.3],
       [ 4.6],
       [ 8.3],
       [ 6.9],
       [ 1.4],
       [10.6],
       [ 3.1],
       [ 2.3],
       [ 6. ],
       [ 6.1],
       [ 3.8],
       [ 3.3],
       [ 9.1],
       [ 2.1],
       [ 1.2],
       [ 7.2],
       [ 5. ],
       [ 4.1]])

In [14]:
x_test

array([[ 1.6],
       [10.4],
       [ 4.2],
       [ 4. ],
       [ 9.6],
       [ 8.8],
       [ 9.7],
       [ 4.1],
       [ 5.4],
       [ 8. ]])

In [15]:
y_train

array([ 56643.,  66030.,  64446.,  61112., 113813.,  91739.,  46206.,
       121873.,  60151.,  39892.,  81364.,  93941.,  57190.,  54446.,
       105583.,  43526.,  39344.,  98274.,  67939.,  56958.])

In [16]:
y_test

array([ 37732., 122392.,  57082.,  63219., 116970., 109432., 112636.,
        55795.,  83089., 101303.])

In [17]:
#Fitting the Simple Linear Regression model to the training dataset  
from sklearn.linear_model import LinearRegression  
regressor= LinearRegression()  
regressor.fit(x_train, y_train)  

LinearRegression()

In [18]:
#Prediction of Test and Training set result  
y_pred= regressor.predict(x_test)  
x_pred= regressor.predict(x_train)  
print(y_pred)

[ 40836.10590871 123080.39940819  65135.55626083  63266.36777221
 115603.64545369 108126.8914992  116538.23969801  64200.96201652
  76350.68719258 100650.1375447 ]


In [19]:
d=regressor.predict([[12.8]])
d

array([145510.66127169])

In [20]:
r_sq = regressor.score(x, y)
print(f"coefficient of determination: {r_sq}")
print(f"intercept: {regressor.intercept_}")
print(f"slope: {regressor.coef_}")

coefficient of determination: 0.9565349708076958
intercept: 25882.59799971892
slope: [9345.94244312]


In [21]:
x_pred

array([ 53920.42532909,  74481.49870396,  56724.20806202,  68873.93323808,
       103453.92027763,  90369.60085726,  38966.91742009, 124949.58789682,
        54855.0195734 ,  47378.2656189 ,  81958.25265845,  82892.84690277,
        61397.17928358,  56724.20806202, 110930.67423213,  45509.07713028,
        37097.72893147,  93173.3835902 ,  72612.31021533,  64200.96201652])

In [22]:
y_pred

array([ 40836.10590871, 123080.39940819,  65135.55626083,  63266.36777221,
       115603.64545369, 108126.8914992 , 116538.23969801,  64200.96201652,
        76350.68719258, 100650.1375447 ])

In [25]:
import joblib

# Assume 'model' is your trained model
joblib.dump(regressor, "model.pkl")
print("Model saved successfully!")


Model saved successfully!
